Repository PAW-KEY/PAWKEY-iOS, pull requests merged in 2025-07, with the labels that each got.

#2 [Feat] #1 Custom TabBar 구현
  PAWKEY/PAWKEY/Application/PAWKEYApp.swift
  PAWKEY/PAWKEY/Global/Component/TabBar/TabBarItem.swift
  PAWKEY/PAWKEY/Global/Component/TabBar/TabBarView.swift
  PAWKEY/PAWKEY/Presentation/ContentView.swift
  PAWKEY/PAWKEY/Presentation/TabView.swift
Labels: Feat, 세민

#10 [Feat] #7 위치 관련 설정 및 LocationManager 추가
  PAWKEY/PAWKEY.xcodeproj/project.pbxproj
  PAWKEY/PAWKEY/Application/PAWKEYApp.swift
  PAWKEY/PAWKEY/Global/Manager/LocationManager.swift
  PAWKEY/PAWKEY/Info.plist
Labels: Add, 석기

#12 [Feat] #11 Pretendard Font 추가 및 설정
  PAWKEY/PAWKEY/Global/Extension/Font+.swift
  PAWKEY/PAWKEY/Global/Resource/Font/Pretendard-Black.otf
  PAWKEY/PAWKEY/Global/Resource/Font/Pretendard-Bold.otf
  PAWKEY/PAWKEY/Global/Resource/Font/Pretendard-ExtraBold.otf
  PAWKEY/PAWKEY/Global/Resource/Font/Pretendard-ExtraLight.otf
  PAWKEY/PAWKEY/Global/Resource/Font/Pretendard-Light.otf
  PAWKEY/PAWKEY/Global/Resource/Font/Pretendard-Medium.otf
  PAWKEY/PAWKEY/Global/Resource/Font/Pretendard-Regular.otf
  PAWKEY/PAWKEY/Global/Resource/Font/Pretendard-SemiBold.otf
  PAWKEY/PAWKEY/Global/Resource/Font/Pretendard-Thin.otf
  PAWKEY/PAWKEY/Info.plist
Labels: Add, 석기

#13 [Feat] #5 Navigation Flow 구현
  PAWKEY/PAWKEY.xcodeproj/project.pbxproj
  PAWKEY/PAWKEY/Global/Router/HomeFlow.swift
  PAWKEY/PAWKEY/Global/Router/MyPageFlow.swift
  PAWKEY/PAWKEY/Global/Router/ScreenEnum.swift
  PAWKEY/PAWKEY/Global/Router/TabRouter.swift
  PAWKEY/PAWKEY/Global/Router/WalkFlow.swift
  PAWKEY/PAWKEY/Presentation/Community/CommunityView.swift
  PAWKEY/PAWKEY/Presentation/Home/View/ChangeMyAreaView.swift
  PAWKEY/PAWKEY/Presentation/Home/View/HomeView.swift
  PAWKEY/PAWKEY/Presentation/Home/ViewModel/.gitkeep
  PAWKEY/PAWKEY/Presentation/MyPage/View/MyPageView.swift
  PAWKEY/PAWKEY/Presentation/MyPage/View/PetProfileView.swift
  PAWKEY/PAWKEY/Presentation/MyPage/View/UserProfileView.swift
  PAWKEY/PAWKEY/Presentation/MyPage/ViewModel/.gitkeep
  PAWKEY/PAWKEY/Presentation/Onboarding/View/LoginView.swift
  PAWKEY/PAWKEY/Presentation/Onboarding/View/OnboardingView.swift
  PAWKEY/PAWKEY/Presentation/Onboarding/View/ProfileSetUpView.swift
  PAWKEY/PAWKEY/Presentation/Onboarding/View/SplashView.swift
  PAWKEY/PAWKEY/Presentation/Onboarding/ViewModel/.gitkeep
  PAWKEY/PAWKEY/Presentation/TabView.swift
  PAWKEY/PAWKEY/Presentation/Walk/CourseDetailView.swift
  PAWKEY/PAWKEY/Presentation/Walk/CourseListView.swift
  PAWKEY/PAWKEY/Presentation/Walk/SharedWalk/View/ReviewWriteView.swift
  PAWKEY/PAWKEY/Presentation/Walk/SharedWalk/View/SharedWalkCompletionView.swift
  PAWKEY/PAWKEY/Presentation/Walk/SharedWalk/View/SharedWalkCourseView.swift
  PAWKEY/PAWKEY/Presentation/Walk/SharedWalk/ViewModel/.gitkeep
  PAWKEY/PAWKEY/Presentation/Walk/Walk/View/ArchiveView.swift
  PAWKEY/PAWKEY/Presentation/Walk/Walk/View/WalkCompletionView.swift
  PAWKEY/PAWKEY/Presentation/Walk/Walk/View/WalkCourseView.swift
  PAWKEY/PAWKEY/Presentation/Walk/Walk/ViewModel/.gitkeep
Labels: Feat, 세민

#23 [Add] #15 Color Assets 나머지 추가
  PAWKEY/PAWKEY/Global/Resource/Assets.xcassets/BW/Contents.json
  PAWKEY/PAWKEY/Global/Resource/Assets.xcassets/BW/pawkey_black.colorset/Contents.json
  PAWKEY/PAWKEY/Global/Resource/Assets.xcassets/BW/pawkey_white1.colorset/Contents.json
  PAWKEY/PAWKEY/Global/Resource/Assets.xcassets/BW/pawkey_white2.colorset/Contents.json
  PAWKEY/PAWKEY/Global/Resource/Assets.xcassets/System Color/Contents.json
  PAWKEY/PAWKEY/Global/Resource/Assets.xcassets/System Color/pawkey_green.colorset/Contents.json
  PAWKEY/PAWKEY/Global/Resource/Assets.xcassets/System Color/pawkey_red.colorset/Contents.json
Labels: Add, 치욱

#26 [Feat] #18 Chip 컴포넌트 추가
  PAWKEY/PAWKEY/Global/Component/Chip.swift
Labels: Feat, 석기

#29 [Add] #28 Main Color 수정
  PAWKEY/PAWKEY/Global/Resource/Assets.xcassets/Green/Contents.json
  PAWKEY/PAWKEY/Global/Resource/Assets.xcassets/Green/green_100.colorset/Contents.json
  PAWKEY/PAWKEY/Global/Resource/Assets.xcassets/Green/green_200.colorset/Contents.json
  PAWKEY/PAWKEY/Global/Resource/Assets.xcassets/Green/green_300.colorset/Contents.json
  PAWKEY/PAWKEY/Global/Resource/Assets.xcassets/Green/green_400.colorset/Contents.json
  PAWKEY/PAWKEY/Global/Resource/Assets.xcassets/Green/green_50.colorset/Contents.json
  PAWKEY/PAWKEY/Global/Resource/Assets.xcassets/Green/green_500.colorset/Contents.json
  PAWKEY/PAWKEY/Global/Resource/Assets.xcassets/Green/green_600.colorset/Contents.json
  PAWKEY/PAWKEY/Global/Resource/Assets.xcassets/Green/green_700.colorset/Contents.json
  PAWKEY/PAWKEY/Global/Resource/Assets.xcassets/Green/green_800.colorset/Contents.json
  PAWKEY/PAWKEY/Global/Resource/Assets.xcassets/Green/green_900.colorset/Contents.json
  PAWKEY/PAWKEY/Global/Resource/Assets.xcassets/Green/green_950.colorset/Contents.json
Labels: Add, 치욱

#34 [Feat] #20 TopNavigation 추가
  PAWKEY/PAWKEY/Global/Modifier/TopNavigationViewModifier.swift
Labels: Feat, 석기

#42 [Feat] #40 SplashView 적용
  PAWKEY/PAWKEY.xcodeproj/project.pbxproj
  PAWKEY/PAWKEY/Global/Resource/Assets.xcassets/appLogo.imageset/Contents.json
  PAWKEY/PAWKEY/Global/Resource/Assets.xcassets/appLogo.imageset/Frame 2087329176-1.png
  PAWKEY/PAWKEY/Global/Resource/Assets.xcassets/appLogo.imageset/Frame 2087329176.png
  PAWKEY/PAWKEY/Global/Resource/Assets.xcassets/appLogo.imageset/Frame 2087329176@3x.png
  PAWKEY/PAWKEY/Info.plist
  PAWKEY/PAWKEY/Presentation/Onboarding/View/Launch Screen.storyboard
  PAWKEY/PAWKEY/Presentation/Onboarding/View/SplashView.swift
  PAWKEY/PAWKEY/Presentation/Walk/Walk/View/WalkCompletionView.swift
  PAWKEY/PAWKEY/Presentation/Walk/Walk/View/WalkCourseView.swift
Labels: Feat, 석기

#48 [Feat] #30 ChoiceButton 추가
  PAWKEY/PAWKEY/Global/Component/Button/ChoiceButton.swift
Labels: Feat, 치욱

#51 [Feat] #49 견주등록 화면 구현
  PAWKEY/PAWKEY.xcodeproj/project.pbxproj
  PAWKEY/PAWKEY/Global/Component/Button/BackButton.swift
  PAWKEY/PAWKEY/Global/Component/Button/ChoiceButton.swift
  PAWKEY/PAWKEY/Global/Component/FlexibleGridView.swift
  PAWKEY/PAWKEY/Global/Component/TextField/PKTextField.swift
  PAWKEY/PAWKEY/Global/Component/TextField/ReviewTextField.swift
  PAWKEY/PAWKEY/Global/Resource/Assets.xcassets/Arrow Button/chevronLeft.imageset/Contents.json
  PAWKEY/PAWKEY/Global/Resource/Assets.xcassets/Arrow Button/chevronLeft.imageset/chevronLeft.png
  PAWKEY/PAWKEY/Global/Resource/Assets.xcassets/Arrow Button/chevronLeft.imageset/ic_chevron_left_24@2x.png
  PAWKEY/PAWKEY/Global/Resource/Assets.xcassets/Arrow Button/chevronLeft.imageset/ic_chevron_left_24@3x.png
  PAWKEY/PAWKEY/Global/Router/OnboardingFlow.swift
  PAWKEY/PAWKEY/Global/Router/ScreenEnum.swift
  PAWKEY/PAWKEY/Presentation/Login/LoginView.swift
  PAWKEY/PAWKEY/Presentation/Onboarding/View/ActivityAreaView.swift
  PAWKEY/PAWKEY/Presentation/Onboarding/View/DogInfoView.swift
  PAWKEY/PAWKEY/Presentation/Onboarding/View/DogTendencyView.swift
  PAWKEY/PAWKEY/Presentation/Onboarding/View/ProfileSetUpView.swift
  PAWKEY/PAWKEY/Presentation/Onboarding/View/UserInfoView.swift
  PAWKEY/PAWKEY/Presentation/Onboarding/ViewModel/ProfileSetUpViewModel.swift
  PAWKEY/PAWKEY/Presentation/Splash/Launch Screen.storyboard
  PAWKEY/PAWKEY/Presentation/Splash/SplashView.swift
Labels: Feat, 석기

#62 [Feat] #54 동네 설정 뷰 구현
  PAWKEY/PAWKEY/Global/Component/ToastMessage.swift
  PAWKEY/PAWKEY/Global/Router/HomeFlow.swift
  PAWKEY/PAWKEY/Global/Router/ScreenEnum.swift
  PAWKEY/PAWKEY/Presentation/Home/View/ActivityAreaMapView.swift
  PAWKEY/PAWKEY/Presentation/Home/View/ChangeMyAreaView.swift
  PAWKEY/PAWKEY/Presentation/Home/ViewModel/ChangeMyAreaViewModel.swift
Labels: Feat, 세민

#65 [Fix] #58 로그인 화면 밀림 현상
  PAWKEY/PAWKEY/Global/Component/Button/CTAButton.swift
  PAWKEY/PAWKEY/Global/Component/TextField/PKTextField.swift
  PAWKEY/PAWKEY/Presentation/Login/LoginView.swift
  PAWKEY/PAWKEY/Presentation/Onboarding/View/OnboardingView.swift
Labels: Fix, 세민

#63 [Feat] #57 산책 코스 옵션 BottomSheet 추가
  PAWKEY/PAWKEY.xcodeproj/project.pbxproj
  PAWKEY/PAWKEY/Global/Component/CheckBoxGroup/CheckBoxGroup.swift
  PAWKEY/PAWKEY/Global/Component/RadioGroup/RadioGroup.swift
  PAWKEY/PAWKEY/Global/Component/WalkHistoryCard.swift
  PAWKEY/PAWKEY/Global/Model/CheckOption.swift
  PAWKEY/PAWKEY/Global/Resource/Assets.xcassets/walkRoute.imageset/Contents.json
  PAWKEY/PAWKEY/Global/Resource/Assets.xcassets/walkRoute.imageset/산책 1.svg
  PAWKEY/PAWKEY/Presentation/Walk/CourseListView.swift
  PAWKEY/PAWKEY/Presentation/Walk/CourseListViewModel.swift
  PAWKEY/PAWKEY/Presentation/Walk/Walk/ViewModel/.gitkeep
  PAWKEY/PAWKEY/Presentation/Walk/WalkOptionSheet.swift
Labels: Feat, 석기

#64 [Feat] #61 SavedRouteView 구현
  PAWKEY/PAWKEY/Global/Component/WalkHistoryCard.swift
  PAWKEY/PAWKEY/Global/Resource/Assets.xcassets/Pet Profile/Contents.json
  PAWKEY/PAWKEY/Global/Resource/Assets.xcassets/Pet Profile/profile.imageset/Contents.json
  PAWKEY/PAWKEY/Global/Resource/Assets.xcassets/Pet Profile/profile.imageset/profile.jpg
  PAWKEY/PAWKEY/Global/Resource/Assets.xcassets/Pet Profile/profile2.imageset/Contents.json
  PAWKEY/PAWKEY/Global/Resource/Assets.xcassets/Pet Profile/profile2.imageset/profile2.jpeg
  PAWKEY/PAWKEY/Global/Resource/Assets.xcassets/Pet Profile/profile3.imageset/Contents.json
  PAWKEY/PAWKEY/Global/Resource/Assets.xcassets/Pet Profile/profile3.imageset/profile3.jpeg
  PAWKEY/PAWKEY/Global/Resource/Assets.xcassets/Pet Profile/profile4.imageset/Contents.json
  PAWKEY/PAWKEY/Global/Resource/Assets.xcassets/Pet Profile/profile4.imageset/profile4.jpeg
  PAWKEY/PAWKEY/Global/Resource/Assets.xcassets/Pet Profile/profile5.imageset/Contents.json
  PAWKEY/PAWKEY/Global/Resource/Assets.xcassets/Pet Profile/profile5.imageset/profile5.jpeg
  PAWKEY/PAWKEY/Global/Resource/Assets.xcassets/Walk Route/walkRoute.imageset/Contents.json
  PAWKEY/PAWKEY/Global/Resource/Assets.xcassets/Walk Route/walkRoute2.imageset/Contents.json
  PAWKEY/PAWKEY/Global/Resource/Assets.xcassets/Walk Route/walkRoute2.imageset/산책2.svg
  PAWKEY/PAWKEY/Global/Resource/Assets.xcassets/Walk Route/walkRoute3.imageset/Contents.json
  PAWKEY/PAWKEY/Global/Resource/Assets.xcassets/Walk Route/walkRoute3.imageset/산책3.svg
  PAWKEY/PAWKEY/Global/Resource/Assets.xcassets/walkRoute.imageset/산책 1.svg
  PAWKEY/PAWKEY/Global/Router/MyPageFlow.swift
  PAWKEY/PAWKEY/Global/Router/ScreenEnum.swift
  PAWKEY/PAWKEY/Presentation/MyPage/View/MyPageView.swift
  PAWKEY/PAWKEY/Presentation/MyPage/View/SavedRouteView.swift
Labels: Feat, 치욱

#70 [Refactor] #69 TimePlaceCell, StatBox 리팩토링
  PAWKEY/PAWKEY/Global/Component/Common/StatBox.swift
  PAWKEY/PAWKEY/Global/Component/Common/TimePlaceCell.swift
  PAWKEY/PAWKEY/Presentation/Walk/View/ArchiveView.swift
  PAWKEY/PAWKEY/Presentation/Walk/View/CourseDetailView.swift
  PAWKEY/PAWKEY/Presentation/Walk/View/WalkCompletionView.swift
  PAWKEY/PAWKEY/Presentation/Walk/View/WalkCourseView.swift
Labels: Refactor, 세민

#76 [Feat] #75 루트 상세화면 구현
  PAWKEY/PAWKEY/Global/Coordinator/HomeCoordinator.swift
  PAWKEY/PAWKEY/Global/Coordinator/ScreenEnum.swift
  PAWKEY/PAWKEY/Presentation/Home/View/HomeView.swift
  PAWKEY/PAWKEY/Presentation/SharedWalk/View/SharedCourseDetailView.swift
  PAWKEY/PAWKEY/Presentation/Walk/View/CourseDetailView.swift
Labels: Feat, 석기

#80 [Feat] #73 WalkCompletionView, ArchiveView GUI 구현
  PAWKEY/PAWKEY/Global/Component/Common/QuestionForm.swift
  PAWKEY/PAWKEY/Global/Component/Common/StatBox.swift
  PAWKEY/PAWKEY/Global/Component/TextField/ReviewTextField.swift
  PAWKEY/PAWKEY/Global/Model/PawPrint.swift
  PAWKEY/PAWKEY/Presentation/Onboarding/OnboardingView.swift
  PAWKEY/PAWKEY/Presentation/Walk/View/ArchiveView.swift
  PAWKEY/PAWKEY/Presentation/Walk/View/WalkCompletionView.swift
  PAWKEY/PAWKEY/Presentation/Walk/View/WalkCourseView.swift
  PAWKEY/PAWKEY/Presentation/Walk/View/WalkMap.swift
  PAWKEY/PAWKEY/Resource/Assets.xcassets/Etc/myLocation.imageset/Contents.json
  PAWKEY/PAWKEY/Resource/Assets.xcassets/Etc/myLocation.imageset/myLocation.png
  PAWKEY/PAWKEY/Resource/Assets.xcassets/Etc/myLocation.imageset/myLocation.svg
Labels: Feat, 세민

#79 [Feat] #78 홈화면 변경된 GUI 반영
  PAWKEY/PAWKEY/Global/Component/Common/ReviewCard.swift
  PAWKEY/PAWKEY/Presentation/Home/View/HomeView.swift
Labels: Feat, 석기

#85 [Fix] #59 회원가입 화면 텍스트필드 가림 현상 수정
  PAWKEY/PAWKEY.xcodeproj/project.pbxproj
  PAWKEY/PAWKEY/Global/Component/TextField/PawkeyTextField.swift
  PAWKEY/PAWKEY/Global/Extension/KeyboardReadable.swift
  PAWKEY/PAWKEY/Global/Extension/UIApplication+.swift
  PAWKEY/PAWKEY/Global/Modifier/TopNavigationViewModifier.swift
  PAWKEY/PAWKEY/Presentation/MyPage/View/MyCourseView.swift
  PAWKEY/PAWKEY/Presentation/Register/View/DogInfoView.swift
  PAWKEY/PAWKEY/Presentation/Register/View/ProfileSetUpView.swift
  PAWKEY/PAWKEY/Presentation/Register/View/UserInfoView.swift
Labels: Fix, 석기

#90 [Fix] #87 산책하기 상단탭 레이아웃 수정
  PAWKEY/PAWKEY.xcodeproj/project.pbxproj
  PAWKEY/PAWKEY/Global/Component/Common/ReviewCard.swift
  PAWKEY/PAWKEY/Presentation/ActivityArea/View/ActivityAreaMapView.swift
  PAWKEY/PAWKEY/Presentation/MapAndList/View/FilterBottomSheet.swift
  PAWKEY/PAWKEY/Presentation/MapAndList/View/MapAndListView.swift
Labels: Fix, 석기

#101 [Network] #99 네트워크 세팅 및 지역 색칠/변경 API 연동
  PAWKEY/PAWKEY.xcodeproj/project.pbxproj
  PAWKEY/PAWKEY.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  PAWKEY/PAWKEY/Application/Config.swift
  PAWKEY/PAWKEY/Global/Extension/MoyaConcurrency.swift
  PAWKEY/PAWKEY/Info.plist
  PAWKEY/PAWKEY/Network/ActivityArea/ActivityAreaMapAPI.swift
  PAWKEY/PAWKEY/Network/ActivityArea/ActivityAreaMapDTO.swift
  PAWKEY/PAWKEY/Network/Base/.gitkeep
  PAWKEY/PAWKEY/Network/Base/BaseDTO.swift
  PAWKEY/PAWKEY/Network/Base/BaseTargetType.swift
  PAWKEY/PAWKEY/Network/Base/NetworkResult.swift
  PAWKEY/PAWKEY/Network/Base/NetworkService.swift
  PAWKEY/PAWKEY/Presentation/ActivityArea/Model/ActivityArea.swift
  PAWKEY/PAWKEY/Presentation/ActivityArea/View/ActivityAreaMapView.swift
  PAWKEY/PAWKEY/Presentation/ActivityArea/ViewModel/ActivityAreaMapViewModel.swift
Labels: Network, 세민

#114 [Feat] #104 공유된 산책 루트 후기 작성 후 나타나는 Alert 구현
  PAWKEY/PAWKEY.xcodeproj/project.pbxproj
  PAWKEY/PAWKEY/Global/Component/Common/Alert.swift
  PAWKEY/PAWKEY/Presentation/SharedWalk/View/ReviewWriteView.swift
  PAWKEY/PAWKEY/Resource/review_check.json
Labels: Feat, 세민

#113 [Network] #105 반려견 성향 카테고리 리스트 조회 API 연동
  PAWKEY/PAWKEY.xcodeproj/project.pbxproj
  PAWKEY/PAWKEY/Network/PetTrait/PetTraitsCategoryAPI.swift
  PAWKEY/PAWKEY/Network/PetTrait/PetTraitsCategoryDTO.swift
  PAWKEY/PAWKEY/Presentation/Register/Model/PetTraits.swift
  PAWKEY/PAWKEY/Presentation/Register/View/DogTendencyView.swift
  PAWKEY/PAWKEY/Presentation/Register/ViewModel/ProfileSetUpViewModel.swift
Labels: Network, 석기

#117 [Network] #110 지역구 리스트 조회 API 연동
  PAWKEY/PAWKEY/Network/Region/RegionAPI.swift
  PAWKEY/PAWKEY/Network/Region/RegionDTO.swift
  PAWKEY/PAWKEY/Presentation/Register/Model/Region.swift
  PAWKEY/PAWKEY/Presentation/Register/View/ActivityAreaView.swift
  PAWKEY/PAWKEY/Presentation/Register/ViewModel/ProfileSetUpViewModel.swift
Labels: Network, 석기

#118 [Network] #111 유저 정보 등록 API 연동
  PAWKEY/PAWKEY/Network/Base/BaseTargetType.swift
  PAWKEY/PAWKEY/Network/Base/LoggingPlugIn.swift
  PAWKEY/PAWKEY/Network/Base/NetworkService.swift
  PAWKEY/PAWKEY/Network/User/RegisterRequestDTO.swift
  PAWKEY/PAWKEY/Network/User/RegisterResponseDTO.swift
  PAWKEY/PAWKEY/Network/User/UserAPI.swift
  PAWKEY/PAWKEY/Network/User/UserDataMapper.swift
  PAWKEY/PAWKEY/Presentation/Register/Model/Gender.swift
  PAWKEY/PAWKEY/Presentation/Register/Model/KnownDogAge.swift
  PAWKEY/PAWKEY/Presentation/Register/Model/UserProfile.swift
  PAWKEY/PAWKEY/Presentation/Register/View/DogInfoView.swift
  PAWKEY/PAWKEY/Presentation/Register/View/ProfileSetUpView.swift
  PAWKEY/PAWKEY/Presentation/Register/View/UserInfoView.swift
  PAWKEY/PAWKEY/Presentation/Register/ViewModel/ProfileSetUpViewModel.swift
Labels: Network, 석기

#123 [Refactor] #120 ReviewCard Chip + 버튼 수정
  PAWKEY/PAWKEY/Global/Component/Common/ReviewCard.swift
  PAWKEY/PAWKEY/Presentation/MyPage/ViewModel/SavedCourseViewModel.swift
Labels: Refactor, 치욱

#126 [Network] #122 공유된 루트 트래킹 정보 조회 API
  PAWKEY/PAWKEY/Network/SharedWalk/SharedWalkCourseAPI.swift
  PAWKEY/PAWKEY/Network/SharedWalk/SharedWalkCourseDTO.swift
  PAWKEY/PAWKEY/Network/Walk/ArchiveDTO.swift
  PAWKEY/PAWKEY/Presentation/SharedWalk/View/SharedWalkCourseView.swift
  PAWKEY/PAWKEY/Presentation/SharedWalk/ViewModel/SharedWalkCourseViewModel.swift
  PAWKEY/PAWKEY/Presentation/Walk/View/ArchiveView.swift
Labels: Network, 세민

#128 [Network] #127 공유된 코스 리뷰 작성하기 API
  PAWKEY/PAWKEY/Network/SharedWalk/ReviewWriteAPI.swift
  PAWKEY/PAWKEY/Network/SharedWalk/ReviewWriteDTO.swift
  PAWKEY/PAWKEY/Presentation/SharedWalk/View/ReviewWriteView.swift
  PAWKEY/PAWKEY/Presentation/SharedWalk/ViewModel/ReviewWriteViewModel.swift
Labels: Network, 세민

#130 [Network] #125 UserProfile API 연결
  PAWKEY/PAWKEY/Global/Coordinator/MyPageCoordinator/MyPageScene.swift
  PAWKEY/PAWKEY/Network/UserProfile/MyUserProfileDTO.swift
  PAWKEY/PAWKEY/Network/UserProfile/UserProfileAPI.swift
  PAWKEY/PAWKEY/Presentation/MyPage/Model/MyUserProfile.swift
  PAWKEY/PAWKEY/Presentation/MyPage/View/MyPageView.swift
  PAWKEY/PAWKEY/Presentation/MyPage/View/PetProfileView.swift
  PAWKEY/PAWKEY/Presentation/MyPage/View/UserProfileView.swift
  PAWKEY/PAWKEY/Presentation/MyPage/ViewModel/UserProfileViewModel.swift
Labels: Network, 치욱

#134 [Network] #109 필터링 카테고리 옵션 조회 API 연동
  PAWKEY/PAWKEY/Global/Component/CheckBox/CheckBoxGroup.swift
  PAWKEY/PAWKEY/Global/Component/Radio/RadioGroup.swift
  PAWKEY/PAWKEY/Network/Filtering/FilterAPI.swift
  PAWKEY/PAWKEY/Network/Filtering/FilterDTO.swift
  PAWKEY/PAWKEY/Network/Filtering/FilterDataMapper.swift
  PAWKEY/PAWKEY/Presentation/MapAndList/Model/Filter.swift
  PAWKEY/PAWKEY/Presentation/MapAndList/View/FilterBottomSheet.swift
  PAWKEY/PAWKEY/Presentation/MapAndList/View/MapAndListView.swift
  PAWKEY/PAWKEY/Presentation/MapAndList/ViewModel/MapAndListViewModel.swift
  PAWKEY/PAWKEY/Presentation/Register/ViewModel/ProfileSetUpViewModel.swift
Labels: Network, 석기

#135 [Network] #108 산책 게시물 리스트 조회 API 연동
  PAWKEY/PAWKEY/Global/Component/Common/ReviewCard.swift
  PAWKEY/PAWKEY/Global/Extension/String+.swift
  PAWKEY/PAWKEY/Network/WalkPost/WalkPostAPI.swift
  PAWKEY/PAWKEY/Network/WalkPost/WalkPostDataMapper.swift
  PAWKEY/PAWKEY/Network/WalkPost/WalkPostRequestDTO.swift
  PAWKEY/PAWKEY/Network/WalkPost/WalkPostResponseDTO.swift
  PAWKEY/PAWKEY/Presentation/MapAndList/Model/MapAndListTab.swift
  PAWKEY/PAWKEY/Presentation/MapAndList/Model/WalkPost.swift
  PAWKEY/PAWKEY/Presentation/MapAndList/View/MapAndListView.swift
  PAWKEY/PAWKEY/Presentation/MapAndList/ViewModel/MapAndListViewModel.swift
  PAWKEY/PAWKEY/Presentation/Register/ViewModel/ProfileSetUpViewModel.swift
  PAWKEY/PAWKEY/Presentation/Walk/ViewModel/WalkCourseViewModel.swift
Labels: Network, 석기

#136 [Network] #131 저장된 산책 게시물 리스트 조회 API 연결
  PAWKEY/PAWKEY/Global/Component/Common/ReviewCard.swift
  PAWKEY/PAWKEY/Network/SavedCourse/SavedCourseAPI.swift
  PAWKEY/PAWKEY/Network/SavedCourse/SavedCourseDTO.swift
  PAWKEY/PAWKEY/Presentation/MyPage/Model/SavedCourse.swift
  PAWKEY/PAWKEY/Presentation/MyPage/View/SavedCourseView.swift
  PAWKEY/PAWKEY/Presentation/MyPage/ViewModel/SavedCourseViewModel.swift
  PAWKEY/PAWKEY/Presentation/Walk/View/CourseDetailView.swift
Labels: Network, 치욱

#137 [Network] #132 내가 기록한 산책 루트 리스트 조회 API 연결
  PAWKEY/PAWKEY/Global/Component/Common/ReviewCard.swift
  PAWKEY/PAWKEY/Network/MyCourse/MyCourseAPI.swift
  PAWKEY/PAWKEY/Network/MyCourse/MyCourseDTO.swift
  PAWKEY/PAWKEY/Presentation/MyPage/Model/MyCourse.swift
  PAWKEY/PAWKEY/Presentation/MyPage/View/MyCourseView.swift
  PAWKEY/PAWKEY/Presentation/MyPage/ViewModel/MyCourseViewModel.swift
Labels: Fix, Network, 치욱

#138 [Network] #107 게시물 상세 조회 API 연동
  PAWKEY/PAWKEY/Global/Coordinator/HomeCoordinator/HomeScene.swift
  PAWKEY/PAWKEY/Global/Coordinator/MyPageCoordinator/MyPageScene.swift
  PAWKEY/PAWKEY/Global/Coordinator/WalkCoordinator/WalkScene.swift
  PAWKEY/PAWKEY/Network/WalkPost/WalkPostAPI.swift
  PAWKEY/PAWKEY/Network/WalkPost/WalkPostDetailResponseDTO.swift
  PAWKEY/PAWKEY/Presentation/MapAndList/View/MapAndListView.swift
  PAWKEY/PAWKEY/Presentation/MyPage/View/MyCourseView.swift
  PAWKEY/PAWKEY/Presentation/MyPage/View/SavedCourseView.swift
  PAWKEY/PAWKEY/Presentation/Walk/Model/Post.swift
  PAWKEY/PAWKEY/Presentation/Walk/View/ArchiveView.swift
  PAWKEY/PAWKEY/Presentation/Walk/View/CourseDetailView.swift
  PAWKEY/PAWKEY/Presentation/Walk/ViewModel/CourseDetailViewModel.swift
Labels: Network, 석기

#142 [Feat] #141 커뮤니티 공사 뷰 구현
  PAWKEY/PAWKEY/Presentation/Community/CommunityView.swift
  PAWKEY/PAWKEY/Resource/Assets.xcassets/Etc/img_community.imageset/Contents.json
  PAWKEY/PAWKEY/Resource/Assets.xcassets/Etc/img_community.imageset/img_community.svg
  PAWKEY/PAWKEY/Resource/Assets.xcassets/Onboarding/onboarding1.imageset/Contents.json
  PAWKEY/PAWKEY/Resource/Assets.xcassets/Onboarding/onboarding1.imageset/onboarding1.png
  PAWKEY/PAWKEY/Resource/Assets.xcassets/Onboarding/onboarding2.imageset/Contents.json
  PAWKEY/PAWKEY/Resource/Assets.xcassets/Onboarding/onboarding2.imageset/onboarding2.png
  PAWKEY/PAWKEY/Resource/Assets.xcassets/Onboarding/onboarding3.imageset/Contents.json
  PAWKEY/PAWKEY/Resource/Assets.xcassets/Onboarding/onboarding3.imageset/onboarding3.png
  PAWKEY/PAWKEY/Resource/Assets.xcassets/Onboarding/onboarding4.imageset/Contents.json
  PAWKEY/PAWKEY/Resource/Assets.xcassets/Onboarding/onboarding4.imageset/onboarding4.png
Labels: Feat, 세민

#144 [Network] #140 산책하기 각 Id 연결 및 디테일 수정
  PAWKEY/PAWKEY/Global/Component/Common/Alert.swift
  PAWKEY/PAWKEY/Global/Coordinator/WalkCoordinator/WalkScene.swift
  PAWKEY/PAWKEY/Presentation/MapAndList/View/MapAndListView.swift
  PAWKEY/PAWKEY/Presentation/Walk/View/ArchiveView.swift
  PAWKEY/PAWKEY/Presentation/Walk/View/WalkCompletionView.swift
  PAWKEY/PAWKEY/Presentation/Walk/View/WalkCourseView.swift
  PAWKEY/PAWKEY/Presentation/Walk/ViewModel/ArchiveViewModel.swift
  PAWKEY/PAWKEY/Presentation/Walk/ViewModel/WalkCompletionViewModel.swift
  PAWKEY/PAWKEY/Presentation/Walk/ViewModel/WalkCourseViewModel.swift
Labels: Network, 세민

#146 [Network] #145 홈 - 지역 변경하기 진입할 경우 지역 선택 API 연동
  PAWKEY/PAWKEY/Global/Coordinator/HomeCoordinator/HomeScene.swift
  PAWKEY/PAWKEY/Network/ActivityArea/ActivityAreaMapAPI.swift
  PAWKEY/PAWKEY/Presentation/ActivityArea/View/ActivityAreaMapView.swift
  PAWKEY/PAWKEY/Presentation/ActivityArea/View/ChangeActivityAreaView.swift
  PAWKEY/PAWKEY/Presentation/ActivityArea/ViewModel/ActivityAreaMapViewModel.swift
  PAWKEY/PAWKEY/Presentation/ActivityArea/ViewModel/ChangeMyAreaViewModel.swift
Labels: Network, 세민

#148 [Network] #106 산책 후기 조회 API 연동
  PAWKEY/PAWKEY/Network/WalkPost/WalkPostAPI.swift
  PAWKEY/PAWKEY/Network/WalkPost/WalkPostDataMapper.swift
  PAWKEY/PAWKEY/Network/WalkPost/WalkPostReviewDTO.swift
  PAWKEY/PAWKEY/Presentation/Walk/Model/Review.swift
  PAWKEY/PAWKEY/Presentation/Walk/View/CourseDetailView.swift
  PAWKEY/PAWKEY/Presentation/Walk/ViewModel/CourseDetailViewModel.swift
Labels: Network, 석기

#151 [Network] #150 홈 현재 지역 조회
  PAWKEY/PAWKEY/Network/Home/MyRegionAPI.swift
  PAWKEY/PAWKEY/Network/Home/MyRegionDTO.swift
  PAWKEY/PAWKEY/Presentation/Home/View/HomeView.swift
  PAWKEY/PAWKEY/Presentation/Home/ViewModel/HomeViewModel.swift
Labels: Network, 세민

#153 [Refactor] 전체 QA
  PAWKEY/PAWKEY/Presentation/Home/View/HomeView.swift
  PAWKEY/PAWKEY/Presentation/Login/View/LoginView.swift
  PAWKEY/PAWKEY/Presentation/MapAndList/View/MapAndListView.swift
  PAWKEY/PAWKEY/Presentation/SharedWalk/View/ReviewWriteView.swift
  PAWKEY/PAWKEY/Presentation/SharedWalk/View/SharedWalkCompletionView.swift
  PAWKEY/PAWKEY/Presentation/Walk/View/WalkCompletionView.swift
Labels: Network, 세민

#157 [Fix] #156 2차 전체 QA
  PAWKEY/PAWKEY/Global/Component/CheckBox/CheckBoxCell.swift
  PAWKEY/PAWKEY/Global/Component/Radio/RadioCell.swift
  PAWKEY/PAWKEY/Global/Coordinator/WalkCoordinator/WalkScene.swift
  PAWKEY/PAWKEY/Global/Extension/String+.swift
  PAWKEY/PAWKEY/Network/Filtering/FilterAPI.swift
  PAWKEY/PAWKEY/Network/Filtering/FilterDTO.swift
  PAWKEY/PAWKEY/Network/WalkPost/WalkPostDetailResponseDTO.swift
  PAWKEY/PAWKEY/Presentation/CourseDetailWrapper/CourseDetailWrapperView.swift
  PAWKEY/PAWKEY/Presentation/MapAndList/View/FilterBottomSheet.swift
  PAWKEY/PAWKEY/Presentation/MapAndList/ViewModel/MapAndListViewModel.swift
  PAWKEY/PAWKEY/Presentation/Onboarding/View/OnboardingView.swift
  PAWKEY/PAWKEY/Presentation/Walk/View/CourseDetailView.swift
  PAWKEY/PAWKEY/Presentation/Walk/ViewModel/WalkCourseViewModel.swift
Labels: Fix, 석기

#160 [Fix] #158 QA 적용 사항 반영
  PAWKEY/PAWKEY/Global/Component/Common/ReviewCard.swift
  PAWKEY/PAWKEY/Network/WalkPost/WalkPostDataMapper.swift
  PAWKEY/PAWKEY/Network/WalkPost/WalkPostResponseDTO.swift
  PAWKEY/PAWKEY/Presentation/CourseDetailWrapper/CourseDetailWrapperView.swift
  PAWKEY/PAWKEY/Presentation/MapAndList/Model/WalkPost.swift
  PAWKEY/PAWKEY/Presentation/MapAndList/View/FilterBottomSheet.swift
  PAWKEY/PAWKEY/Presentation/MapAndList/View/MapAndListView.swift
  PAWKEY/PAWKEY/Presentation/MapAndList/ViewModel/MapAndListViewModel.swift
  PAWKEY/PAWKEY/Presentation/Walk/View/CourseDetailView.swift
  PAWKEY/PAWKEY/Presentation/Walk/ViewModel/CourseDetailViewModel.swift
Labels: Fix, 석기

#164 [Fix] #161 공유 산책 뷰에서 리뷰 작성 뷰까지 routeId 전달 및 디테일 수정
  PAWKEY/PAWKEY/Global/Component/Common/ReviewCard.swift
  PAWKEY/PAWKEY/Global/Coordinator/WalkCoordinator/WalkScene.swift
  PAWKEY/PAWKEY/Presentation/Home/View/HomeView.swift
  PAWKEY/PAWKEY/Presentation/Onboarding/View/OnboardingView.swift
  PAWKEY/PAWKEY/Presentation/SharedWalk/View/ReviewWriteView.swift
  PAWKEY/PAWKEY/Presentation/SharedWalk/View/SharedWalkCompletionView.swift
  PAWKEY/PAWKEY/Presentation/SharedWalk/View/SharedWalkCourseView.swift
  PAWKEY/PAWKEY/Presentation/SharedWalk/ViewModel/ReviewWriteViewModel.swift
  PAWKEY/PAWKEY/Presentation/SharedWalk/ViewModel/SharedWalkCompletionViewModel.swift
  PAWKEY/PAWKEY/Presentation/SharedWalk/ViewModel/SharedWalkCourseViewModel.swift
  PAWKEY/PAWKEY/Presentation/Walk/View/CourseDetailView.swift
  PAWKEY/PAWKEY/Presentation/Walk/ViewModel/WalkCourseViewModel.swift
Labels: Fix, 세민
